source 'https://github.com/CocoaPods/Specs.git'

# Specify Swift version
platform :ios, '12.0'
# use_frameworks!

def shared_pods
  pod "Tonylyliu_MWPhotoBrowser", :path => "../"
end

target 'MWPhotoBrowser_Example' do
  shared_pods
end

target 'MWPhotoBrowser_Tests' do
  shared_pods
  
  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase/Core', '~> 2.1.4'  # Use Core subspec which is pure Objective-C
  pod 'Expecta+Snapshots'
end
