source 'https://github.com/CocoaPods/Specs.git'

# Specify Swift version
platform :ios, '12.0'
# use_frameworks!

def shared_pods
  pod "Tonylyliu_MWPhotoBrowser", :path => "../"
end

target 'MWPhotoBrowser_Example' do
  shared_pods
end

target 'MWPhotoBrowser_Tests' do
  shared_pods
  
  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase/Core', '~> 2.1.4'  # Use Core subspec which is pure Objective-C
  pod 'Expecta+Snapshots'
end

# Force all pods to use iOS 12.0 minimum
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET[arch=*]'] = '$(inherited)'
      if target.name == 'MWPhotoBrowser_Tests'
        config.build_settings['CLANG_ENABLE_MODULES'] = 'NO'  # Disable Swift modules
      end
      # Disable ARC runtime library
      config.build_settings['CLANG_ENABLE_OBJC_ARC'] = 'YES'
      config.build_settings['CLANG_ENABLE_OBJC_WEAK'] = 'YES'
      config.build_settings['CLANG_LINK_OBJC_RUNTIME'] = 'NO'
    end
  end
end
